# Imagen base
FROM maven:3.9.9-eclipse-temurin-21

# Establece directorio de trabajo
WORKDIR /app

# # Copia el resto del código fuente
# COPY . .

# Copia solo los archivos necesarios para la instalación de dependencias
COPY pom.xml .
COPY src ./src

# # Instala dependencias
# RUN mvn clean install

# Instala dependencias
RUN mvn dependency:go-offline

# Expone el puerto
EXPOSE 8080

# Comando para iniciar la aplicación
CMD ["mvn", "spring-boot:run"]
