spring.config.import=optional:file:.env[.properties]
spring.application.name=vitaltrail

server.port=${SERVER_PORT}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Generación automática del esquema
# spring.jpa.hibernate.ddl-auto=update

# Habilita Hibernate para manejar correctamente UUIDs
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Habilita Hibernate para respetar el mapeo de UUIDs a strings
spring.jpa.properties.hibernate.type.handling.mode=allow

# Habilita la impresión de las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
